### ISSUE TITLE
error with new versions of flask

### ISSUE THREAD

**Issue by coderMohammed1** [noraj/flask-session-cookie-manager#17]
```
Traceback (most recent call last):
  File "/home/coder/htb/spider/flas.py", line 1, in <module>
    from flask import Flask, session
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/coder/.local/lib/python3.11/site-packages/werkzeug/urls.py)
```

---

solution: downgrade your flask and werkzeug to version 2.0.3:

pip3 install werkzeug==2.0.3

pip3 install flask==2.0.3

this will work but it might break other apps u have! so create python virtual environment.

**Comment by noraj** [comment]
Works well with flask 3.1.0 and werkzeug 3.1.3

**Comment by coderMohammed1** [comment]
good, I just wanted to point this out, as it wasted lots of time to figure out, hope u make this clear on the readme!
